splitting pipeline processes a little

diff --git a/.github/workflows/prod-build-and-deploy.yaml b/.github/workflows/prod-build-and-deploy.yaml
--- a/.github/workflows/prod-build-and-deploy.yaml
+++ b/.github/workflows/prod-build-and-deploy.yaml
@@ -60,7 +60,7 @@ jobs:
           fail-on-empty: false
 
   #Runs Creates cointainer from Docker File and Pushes it to VPS
-  build-and-push:
+  build-and-push-image:
     needs: build-and-test
     runs-on: ubuntu-latest
     steps:
@@ -94,7 +94,7 @@ jobs:
               version="prod-${{ github.event.release.tag_name || github.run_number }}"
               docker push ghcr.io/${owner}/prod-safebite-api:${version}
               docker push ghcr.io/${owner}/prod-safebite-api:latest
-  deploy:
+  deploy-to-vps:
     needs: build-and-push
     runs-on: ubuntu-latest
     environment: VPS_PROD
@@ -142,13 +142,24 @@ jobs:
             -e Email__EnableSsl='true' \
             --name "${container_name}" ghcr.io/${owner}/prod-safebite-api:${version}
 
-            echo "API Healthcheck"
             sleep 10
+            echo "Deployed"
 
-            status_code=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost:8443/api/HealthCheck)
-            if [ "$status_code" = "200" ]; then
-              echo "Healthcheck OK (200) - Deployed."
-            else
-              echo "Healthcheck FAILED (HTTP $status_code) - Deployment failed."
-              exit 1
-            fi
+  peform-healthcheck:
+    needs: deploy-to-vps
+    runs-on: ubuntu-latest
+    steps:
+      - name: Wait for API healthcheck
+        run: |
+            set -e
+            for i in {1..15}; do
+              status_code=$(curl -k -s -o /dev/null -w "%{http_code}" "https://prod.chimpchonkserver.duckdns.org/api/healthcheck" || true)
+              echo "Attempt $i - HTTP status: $status_code"
+              if [ "$status_code" = "200" ]; then
+                echo "Healthcheck OK (200)."
+                exit 0
+              fi
+              sleep 2
+            done
+            echo "Healthcheck failed (never got HTTP 200)."
+            exit 1
